CREATE TABLE terms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  image TEXT,
  icon TEXT NOT NULL,
  description VARCHAR(3000),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_terms_name_not_empty CHECK (char_length(TRIM(name)) > 0),
  CONSTRAINT chk_terms_icon_not_empty CHECK (char_length(TRIM(icon)) > 0)
);

CREATE TABLE term_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_term_categories_name_not_empty CHECK (char_length(TRIM(name)) > 0)
);

CREATE TABLE term_category_links (
  term_id UUID NOT NULL REFERENCES terms(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES term_categories(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (term_id, category_id)
);

CREATE TABLE term_attributes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  term_id UUID NOT NULL REFERENCES terms(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  value TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_term_category_links_category_id
ON term_category_links(category_id);

CREATE UNIQUE INDEX uq_term_categories_name_normalized
ON term_categories (LOWER(TRIM(name)));

CREATE INDEX idx_term_attributes_term_id
ON term_attributes(term_id);

CREATE TRIGGER trg_terms_updated_at
BEFORE UPDATE ON terms
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
